name: build-image
on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  OPENWRT_ROOTFS_URL: https://archive.openwrt.org/releases/19.07.10/targets/x86/64/openwrt-19.07.10-x86-64-generic-rootfs.tar.gz

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Import OpenWRT rootfs
        run: |
          docker import ${{ env.OPENWRT_ROOTFS_URL }} local/openwrt-rootfs
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile
          tags: ghcr.io/${{ env.IMAGE_NAME }}/openwrt:latest

